### ISSUE TITLE
Resesif Atom version.

### ISSUE THREAD

**Issue by carloscuesta** [carloscuesta/resesif#2]
Create a Resesif version for Github's [Atom](https://limhenry.me).

**Comment by jchook** [comment]
+1. Right now the line bg color is awkwardly not the full line-height and overlaps the selection highlight. I've also noticed that some syntax highlighting is missing such as Markdown.

**Comment by carloscuesta** [comment]
@jchook Can you provide some screenshots? My line highlight is the full line-height.

<img width="540" alt="screen shot 2016-01-18 at 15 15 37" src="https://cloud.githubusercontent.com/assets/7629661/12393504/61b57cf8-bdf6-11e5-8bfa-27944b7143e4.png">

The Markdown syntax highlight it's included, but you will need to install [Markdown Extended](https://packagecontrol.io/packages/Markdown%20Extended)

<img width="622" alt="screen shot 2016-01-18 at 15 19 59" src="https://cloud.githubusercontent.com/assets/7629661/12393596/fdc8ee0e-bdf6-11e5-8bb5-8400a9f1bcee.png">

Feel free to contribute in the Atom version :+1:
